---
title: "gbs_pipeline"
author: "Eddy"
date: "18/2/2022"
output:
  html_document: default
  pdf_document: default
---


```{r}
library(tidyverse)
library(adegenet)
library(MetBrewer)
library(reshape2)
getwd()
```

```{r}
pca <- read_table2("../vanilla4.eigenvec", col_names = FALSE)
eigenval <- scan("../vanilla4.eigenval")
# sort out the pca data
# remove nuisance column
pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))
```

```{bash}
grep "mexi" ../sra_vanilla.csv | cut -f 1 -d $',' 
```
```{bash}
grep "plani" ../sra_vanilla.csv | cut -f 1 -d $',' 
```

```{r}
# sort out the individual species and pops
# spp

spp <- rep(NA, length(pca$ind))

for(i in c("SRR8257312", "SRR8257336")) {
spp[grep(i, pca$ind)] <- "V._mexicana"
}

for(i in c(
"SRR8257273",
"SRR8257266",
"SRR8257232",
"SRR8257282",
"SRR8257284",
"SRR8257294",
"SRR8257250",
"SRR8257262",
"SRR8257265",
"SRR8257321",
"SRR8257317",
"SRR8257315",
"SRR8257314",
"SRR8257239",
"SRR8257242",
"SRR8257244",
"SRR8257236"
           )) {
spp[grep(i, pca$ind)] <- "V._planifolia_uno"
}


for(i in c(
"SRR8257237",
"SRR8257307",
"SRR8257306",
"SRR8257309",
"SRR8257308",
"SRR8257327",
"SRR8257326",
"SRR8257300",
"SRR8257346",
"SRR8257345",
"SRR8257334",
"SRR8257335",
"SRR8257340",
"SRR8257341",
"SRR8257338",
"SRR8257339",
"SRR8257343",
"SRR8257332"
           )) {
spp[grep(i, pca$ind)] <- "V._planifolia_dos"
}
spp

pca <- as.tibble(data.frame(spp, pca))
pca
```

```{r}
pve <- data.frame(PC = 1:20, pve = eigenval/sum(eigenval)*100)
ggplot(pve, aes(PC, pve)) + geom_bar(stat = "identity") + ylab("Percentage variance explained") 
```

```{r}
ggplot(pca, aes(PC1, PC2, col = spp, label=ind)) + geom_point(size=5) + labs(x="PC1 (87.52%)", y="PC2 (6.03%)") + geom_text()
```

```{r}
cvad=read.table("../vanilla_admix_cv.txt")
cvad$V1[cvad$V2 == min(cvad$V2)]
cvad
ggplot(cvad) + geom_line(aes(V1, V2), size=2, color="green") + geom_point(aes(V1, V2), size=4, color="blue") +
  labs(x="K", y="Error")
```

```{r}
tbl2k=read.table("../pop.admix.2.Q")
spadmix2 = mutate(tbl2k, sp = c(rep("V_mexicana", 2), rep("V_planifolia", 35)))
spadmix2$id = rownames(spadmix2)
admix2=melt(spadmix2)

ggplot(admix2) + 
  geom_bar(aes(id, value, fill=variable), position = "stack", stat = "identity", width=1) + 
  scale_fill_manual(values=met.brewer("Pissaro", 2)) +
  theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), legend.position = "none")+
  labs(title = "K=2", y= "Ancestry probability", x= NULL)
```

```{r}
tbl4k=read.table("../pop.admix.4.Q")
spadmix = mutate(tbl4k, sp = c(rep("V_mexicana", 2), rep("V_planifolia", 35)))
spadmix$id = rownames(spadmix)
admix=melt(spadmix)

ggplot(admix) + 
  geom_bar(aes(id, value, fill=variable), position = "stack", stat = "identity", width=1) + 
  scale_fill_manual(values=met.brewer("Pissaro", 4)) +
  theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), legend.position = "none")+
  labs(title= "K=4", y= "Ancestry probability", x= NULL)
```

```{r}
stck=read.table("../vani_4.4k.stacks.txt")
stadmix = mutate(stck, sp = c(rep("V_planifolia", 3), "weird", rep("V_planifolia", 27)) )
stadmix$id = rownames(stadmix)
cadmix=melt(stadmix)

ggplot(cadmix[order(cadmix$sp),]) + 
  geom_bar(aes(id, value, fill=variable), position = "stack", stat = "identity", width=1) + 
  scale_fill_manual(values=met.brewer("Pissaro", 4)) +
  theme(axis.ticks.x=element_blank(), legend.position = "none")+
  labs(title= "K=4", y= "Ancestry probability", x= NULL) 
```

```{r}
tbl8k=read.table("../pop.admix.8.Q")
spadmix8 = mutate(tbl8k, sp = c(rep("V_mexicana", 2), rep("V_planifolia", 35)))
spadmix8$id = rownames(spadmix8)
admix8=melt(spadmix8)

ggplot(admix8) + 
  geom_bar(aes(id, value, fill=variable), position = "stack", stat = "identity", width=1) + 
  scale_fill_manual(values=met.brewer("Pissaro", 8)) +
  theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), legend.position = "none")+
  labs(title= "K=8", y= "Ancestry probability", x= NULL)
```

```{r}
tbl19k=read.table("../pop.admix.19.Q")
spadmix19 = mutate(tbl19k, sp = c(rep("V_mexicana", 2), rep("V_planifolia", 35)))
spadmix19$id = rownames(spadmix19)
admix19=melt(spadmix19)

ggplot(admix19) + 
  geom_bar(aes(id, value, fill=variable), position = "stack", stat = "identity", width=1) + 
  scale_fill_manual(values=met.brewer("Pissaro", 19)) +
  theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), legend.position = "none")+
  labs(title="K=19", fill= "Population", y= "Ancestry probability", x= NULL, fill=NULL)
```
